### ISSUE TITLE
Image Story: image too small

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#10]
Hier habe ich zwei solcher Image Story verwendet - für Feature und Applications

https://drhubert.netlify.app/serie-a1110-40-qe-a

Hier finde ich das Bild zu klein und rechts neben dem Bild ist ein Spacing, welches nicht beeinflusst werden kann.

**Comment by fleven-kds** [comment]
Hier pfuscht das Image Resizing wieder in die Component Darstellung @julrich

**Comment by julrich** [comment]
@fleven-kds @DanielLeyUX könnt ihr das aktuell noch reproduzieren? Ich habe auf meiner Test-Seite mal eine Image Story eingesetzt, die scheint zu funktionieren:
https://drhubert.netlify.app/jonas-test

Habe ansonsten nur auf der Seite hier eine gefunden, die scheint aber auch wie gewünscht zu funktionieren... oder?
https://drhubert.netlify.app/produkte-uebersicht/serie-a1110-40-qe-a

**Comment by DanielLeyUX** [comment]
jo, klappt!
