### ISSUE TITLE
Tag Label: cut off in Slider Sections 

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#11]
Please add some inner spacing, so that the label is not cut off

![image](https://github.com/user-attachments/assets/8d3afe7d-6d19-40ff-aea3-0528ff9896dd)

**Comment by fleven-kds** [comment]
Das Slider Layout der Section hat nun generell mehr inneres top-spacing, daher sollte man das spaceBefore entsprechend verwenden um zu viel eventuellen Weißraum auszugleichen.
