### ISSUE TITLE
Anchor Links / Headline IDs

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#13]
Bei ruhmesmeile festgestellt und merke ich hier wieder. Es ist "nervig", dass unsere Section HEadlines keine IDs haben, die ich für Anchor-Naviagtion nutzen kann. das funktioniert nur bei den Markdown Headlines aus den Text Komponenten, bei denen Storyblok dann eine ID in das H-Tag einfügt. 

wäre der Aufwand in einem vertretbaren Rahmen, dass für den Storyblok Starter allgemein umzustzen?  Beu Euffinger haben wir ja den OnePager, da schlägt das auch zu Gute.

**Comment by julrich** [comment]
TBD: https://developers.google.com/style/headings-targets

**Comment by DanielLeyUX** [comment]
![image](https://github.com/user-attachments/assets/16411aa7-f6e9-43e2-809a-cf3b62943335)

Seit dem Change sind die Headlines jetzt immer selbst Links auf sich selbst :D

**Comment by julrich** [comment]
Das ist quasi "korrekt", um den Link kopieren zu können. Das müsste man aber auch noch besser stylen / darstellen. So kannst du z.B. (mache ich manchmal) draufklicken, und dann die URL aus der URL-Leiste kopieren (Strg-L + Strg+C).

Und so ist es eben auch nicht wirklich korrekt / accessible ;) Das muss man dann eh noch mal gucken, wie man das beides verbindet. Weil dafür den Source der Seite inspecten zu müssen (um den Anchor-Link zu finden) fänd ich jetzt nicht sehr Nutzer-freundlich :D

**Comment by julrich** [comment]
Relevant links:
* https://developers.google.com/style/headings-targets
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

**Comment by lmestel** [comment]
done
