### ISSUE TITLE
Icon-Picker Add-On

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#15]
Wir haben die neuen Icons integriert. Im Features Element kann ich die manuell eingeben und die neuen Icons werden gezogen. 

Beim CTA Element hingegen ist der Icon Picker integriert, der greift noch auf das alte Sprite zu: 

![image](https://github.com/user-attachments/assets/41ad8c44-c920-4b77-a2b6-d48812975016)

Aus Konsistenz-Gründen sollten wir überall den Icon Picker integrieren, wo Icons auswählbar sind.
Der Icon-Picker sollte sich der neuen Icons bedienen.

**Comment by lmestel** [comment]
Wenn sich Icons geändert haben, muss man einmal mit `npm run build-tokens` das Icon-Sprite neu generieren und den Inhalt der Datei `token/icon-sprite.html` in Storyblok in die "Global Settings" Story kopieren.

![grafik](https://github.com/user-attachments/assets/ed89aeed-1cca-4240-b3be-ed95d69f252a)
