### ISSUE TITLE
Table: style and design table layout

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#2]
to fit the overall style and design please customize the table CSS. background should alternate. table head should differ

| Syntax      | Description | Test Text     |
| :---        |    :----:   |          ---: |
| Header      | Title       | Here's this   |
| Paragraph   | Text        | And more      |

**Comment by fleven-kds** [comment]
Overrhauled style
<img width="802" alt="Screenshot 2024-10-08 at 13 53 35" src="https://github.com/user-attachments/assets/40b5fa7b-e584-4e27-bd42-7e60c73ba8da">

**Comment by DanielLeyUX** [comment]
prima!
