### ISSUE TITLE
HTML embed Komponente erstellen

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#22]
Zum Einpflegen von externen Inhalten, wie Maps, Videos, Scripts (zammad) braucht es noch die HTML Komponente

**Comment by julrich** [comment]
Komponente existierte bereits, war aber Storyblok noch nicht bekannt gemacht. Das habe ich jetzt mal für Dr Hubert nachgeholt. Gerne mal testen, ob sich das verhält wie gewünscht.

Gegebenenfalls müssen wir noch was an den Security-Einstellungen der Seite ändern, damit dritte URLs da erlaubt werden. Aber erstmal testen!

**Comment by julrich** [comment]
See also: #6
