### ISSUE TITLE
Fix Layout / CSS buggy behaviors

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#25]
- [x] Main nav duplication
- [x] Font rendering issues

**Comment by julrich** [comment]
Vor allem das Rendering der Font (im Header?) ist hier teilweise augenscheinlich noch nicht korrekt, und springt teilweise ein wenig unerwartet.

**Comment by DanielLeyUX** [comment]
Font rendering issues seem to be fixed now. But whilst testing on https://drhubert.netlify.app/ I saw, that active states for the menu is not working properly. Sometime it works (as for ANwednungen) but mostly it does not highlight the main menu item as active

**Comment by fleven-kds** [comment]
> Font rendering issues seem to be fixed now. But whilst testing on https://drhubert.netlify.app/ I saw, that active states for the menu is not working properly. Sometime it works (as for ANwednungen) but mostly it does not highlight the main menu item as active

This is an unrelated issue referenced in #32
