### ISSUE TITLE
Permalinks - display none

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#26]
Normally, I would recommend to use a chain-symbol before the headline, similar to what Gatsby ot m3-Materials is doing in their docs. And we should keep this in mind for other projects. in regards to the time left, I would for Hubert, just not display the '#'

![image](https://github.com/user-attachments/assets/66f22b5a-bbaa-4ef0-b4cb-d9f3dc681da9)

**Comment by julrich** [comment]
@fleven-kds das ist schon erledigt, oder?

**Comment by fleven-kds** [comment]
Ja, ist done!
