### ISSUE TITLE
Teaser-Card / Link auf Asset

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#27]
auf der Seite: https://drhubert.netlify.app/use-cases#

Für die 1. Teaser-Card wurde ein Link zu einem PDF aus den Assets hinterlegt. Klick öffnet aber leider nichts.

PDF kann man aber testen auf der Über Uns Seite dort im Copy-Text gibt es einen Text-Link auf das ISO PDF, das klappt.

**Comment by julrich** [comment]
Das scheint einfach bisher übersehen gewesen zu sein in unserer Integration, Asset-Links handlen wir einfach noch nicht:
https://github.com/kickstartDS/dr-hubert-website/blob/main/helpers/storyblok.ts#L95-L113

Sollte aber ein einfacher Fix sein, und wird ja auch allgemein benötigt.

(hat das bei `ruhmesmeile` btw. nicht funktioniert?)

**Comment by julrich** [comment]
Fixed here: https://github.com/kickstartDS/dr-hubert-website/commit/13bb796b89ebf9033b70bd339a274b9a9c34d60e

Damit das im Starter zukünftig auch korrekt hinterlegt ist, hier ein Ticket: https://github.com/kickstartDS/storyblok-starter/issues/33
