### ISSUE TITLE
Header Navi inkonsistente Ausgabe im CMS

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#28]
Bei den `NavItems` kam die Frage auf, warum bei manchen das Label des jeweiligen Items darunter ausgelesen wird (zB Knowledgebase, Kontakt und bei anderen steht da nur `navItems`, egal ob ein Ordner mit SubNavitems verlinkt ist oder wie bei Über Uns eine Story im Root

![image](https://github.com/user-attachments/assets/c699f673-033d-4fbf-8968-21eb9acfa998)

**Comment by julrich** [comment]
Explizit jetzt hier im Projekt behoben, durch die Anpassung des `Preview field`:
<img width="246" alt="image" src="https://github.com/user-attachments/assets/a602e765-c61c-41be-abb9-3946e52aecd1">
<img width="496" alt="image" src="https://github.com/user-attachments/assets/ddb2c803-ead5-4c6a-9f53-244d8504b056">

Muss dann aber auch mal generell angepasst, werden. Es gibt bereits ein Ticket für Preview Templates / Fields im Premium Starter:
https://github.com/kickstartDS/storyblok-starter/issues/28
