### ISSUE TITLE
Actice State in preview inconsistent

### ISSUE THREAD

**Issue by fleven-kds** [kickstartDS/dr-hubert-website#32]
The active state of the main level navigation only seems to be working when visiting the pages `Support`, `Wissen` & `Über uns`.

This was noticed in the PREVIEW deployment:
https://drhubert.netlify.app/support
https://drhubert.netlify.app/wissen

**Comment by fleven-kds** [comment]
A possible explanaition could be the page title:
<img width="469" alt="Screenshot 2024-11-04 at 14 48 46" src="https://github.com/user-attachments/assets/67c96c2c-b830-4291-bac2-a548ad322490">
<img width="487" alt="Screenshot 2024-11-04 at 14 48 51" src="https://github.com/user-attachments/assets/52435209-4da1-4454-a4c8-65ffbf104f7e">

**Comment by julrich** [comment]
Detection was way too naive here (did not respect all combinations of trailing and leading slashes in both the current URL as well as the menu href). Fixed now!
