### ISSUE TITLE
Support für `<sup>` and `<sub>` in Markdown-Feldern in Firefox fehlerhaft

### ISSUE THREAD

**Issue by julrich** [kickstartDS/dr-hubert-website#34]
Anstatt tatsächlich hoch- / tiefgestellten Text darzustellen:
![image](https://github.com/user-attachments/assets/33a24ff5-b4cf-49a9-91ba-34c93ea1bf1c)

Wird im Firefox kaputtes Markup gerendered:
![image](https://github.com/user-attachments/assets/07dba85c-54a0-441c-9cb4-46c94baaeaff)

**Comment by julrich** [comment]
Initial ausgeliefertes HTML sieht für beide Browser korrekt aus:
```html
<div class="c-rich-text dsa-text"><div><p>Test eines hochgestellten <sup>Texts</sup></p><p>Test eines tiefgestellten A<sub>var</sub></p></div></div>
```

Aber im Firefox (Devtools) landet dann schlussendlich das hier?!
<img width="145" alt="image" src="https://github.com/user-attachments/assets/d4f5fa47-bb04-41a8-9779-c2315e941ce1">

**Comment by julrich** [comment]
Link to test: https://drhubert.netlify.app/sales

**Comment by lmestel** [comment]
Das Problem scheint an der Markdown-Library zu liegen. Ein ähnlicher Fehler wurde dort auch schon gemeldet: https://github.com/quantizor/markdown-to-jsx/issues/542

Ein Update der Library sollte das Problem lösen.

**Comment by lmestel** [comment]
Das Update der Library hat den Fehler behoben
