### ISSUE TITLE
Icon-Picker integrieren

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#35]
Bitte noch den Icon Picker integrieren. Bei zB der Facts-Komponente fehlt dieser

<img width="518" alt="image" src="https://github.com/user-attachments/assets/cc49ffd3-964b-4931-bb2d-a6a75d7ce9e7">

**Comment by julrich** [comment]
Ich vermute fast, dass wir das erst nach Hubert finalisiert hatten mit dem Picker... und deswegen hier einfach noch an einigen Stellen das Icon noch nicht manuell eingestellt wurde für Komponenten (also in deren Block-Schema) bei Hubert.

Das gleiche ich noch mal ab!

**Comment by julrich** [comment]
Ist jetzt auch zu den restlichen Komponenten hinzugefügt manuell. Sollte jetzt überall passen!
