### ISSUE TITLE
Slider: enlarge left/right arrows 

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#4]
For Slideshows, and I guess the slider component we should enlarge the icons of the chevrons for better visibility. 

status quo:
![image](https://github.com/user-attachments/assets/3d87d8c1-f085-4f54-8373-d5c3bb51fa83)

**Comment by fleven-kds** [comment]
I increased the icon size to 4rem:
<img width="1413" alt="Screenshot 2024-10-08 at 13 38 58" src="https://github.com/user-attachments/assets/95d64d63-e833-4596-9c91-a0f62f005fee">

The Buttons still have a visibility problem when the content is dark:
<img width="979" alt="Screenshot 2024-10-08 at 13 39 30" src="https://github.com/user-attachments/assets/c929d34f-bf51-4f15-bf05-f49a3330a2e5">

**Comment by fleven-kds** [comment]
The style also diverts from the lightbox arrows being styled in #12 :
<img width="1892" alt="Screenshot 2024-10-08 at 13 40 32" src="https://github.com/user-attachments/assets/08ae149c-bd08-477e-9cc7-354a144af904">
