### ISSUE TITLE
Slider-Component: 2. Image not loaded

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#5]
On the Hubert LP you can find a freshly added Slider containing 2 heroes. The second item does not show the image selected in hero (whereas it is displayed in the hero section below)

![image](https://github.com/user-attachments/assets/4f792f0e-f23f-4d11-aff3-652db2bf543a)

**Comment by julrich** [comment]
This should affect every `Hero`, not specifically elements inside the slider. The initial hero presets all have an image added for `src`, which should not be the case. Needs to be fixed.

Workaround... add an image for `src` and immediately remove it again.

**Comment by julrich** [comment]
Affected `Hero` presets were fixed right inside the system (-> add component with "defective" preset in Visual Editor -> change wrong content / settings to fix it -> edit the presets right from the editor controls in the Visual Editor -> select "fill preset with current component configuration").

General issue for this tracked here: https://github.com/kickstartDS/storyblok-starter/issues/32
