### ISSUE TITLE
Header-Menu: add active state

### ISSUE THREAD

**Issue by DanielLeyUX** [kickstartDS/dr-hubert-website#8]
please add visual indication which main page  is active. 

We designed this once: 
![image](https://github.com/user-attachments/assets/7edb78cc-bb70-4f37-a6b0-7b5dd8b16b3d)

could be also a underline similar to what we have on ruhmesmeile.com

**Comment by DanielLeyUX** [comment]
das aus dem Screenshot passt aber mE. design-konzeptionell nicht mehr zum Look.

**Comment by fleven-kds** [comment]
Es gibt bereits styles für einen active state welcher so aussieht:
<img width="1431" alt="Screenshot 2024-10-08 at 13 58 41" src="https://github.com/user-attachments/assets/7032e6a3-e118-4878-b1ba-d8320be5cc95">

Ich bin mir nicht sicher ob die active state Klasse nicht gesetzt wird, da wir nur auf die preview gucken können oder ob es dafür einfach noch keine Systematik gibt. Veilleicht weiß @julrich da mehr?

**Comment by julrich** [comment]
Das ist, so weit ich das beurteilen kann, bereits alles eingebaut und funktional:
<img width="524" alt="image" src="https://github.com/user-attachments/assets/bed7e7ea-5911-4571-b675-4942723b1a69">

Im Menü sind halt nicht so all zu viele Links, die tatsächlich korrekt verknüft wurden... aber hier geht es bei mir (inkl. Untermenü):
https://drhubert.netlify.app/produkte-uebersicht/produkte
